os: linux
language: cpp
sudo: required
branches:
  only:
  - "/^test.*$/"
  - "/^v.*$/"
services:
- docker
addons:
  apt:
    update: true
env:
  global:
  - DOCKERHUB='chalmersfsd'
  - IMAGE=`echo ${TRAVIS_REPO_SLUG#*/}`
  - secure: jKkdsxVonZgxeopGTXPAX2ZSRufcS9BjOuoiEd6MUQj1D7SOsA40Q5qFsg5orVvSN8PJKQV7RYU5UXHaFQaqXf0ymJaBSc+2Wcozu+KG/nOYK696MOeOVDoHp8KOfa5ULgirGGUg5h4V3YWgl57db9bAewciyJ8HXrrqzuFsHEO8laSRv8CL2S43/KzCDM8GnzgR0O/J6rrryGoC45BJdUTfSccLk4YuQbBxCtndAlYK3R9SgDgq9GaXwfSmGEQXRN7E99JDGWzY3pG8SIpWqWiegOmZKCYykYaDR4604pGo3dEwYF5Svw5E492+1FRpZorRdBNwgb3pqiHTbYiBfR4a+y3aEgII7Fqli4zImvY6T9/61MxPKifv1uPHIn+SKbs+whWX2V8QGqdHPi584PHdkpMI4tQnnYXJ8XQbzPRyIfiRNMl1aQEIykqZoM9Ung2MGAkeoUMeqKlfApaTlu7MqqbQtuNgevYvkyPBKtT3CJL68s/+UJFCAQMQyrcWPxf6iQO9AEMOAU478xyhdh5hdjV/X/O5uy2zriQuSmfG9ZI7LyCBFAEhtctbi/V2xYNrSCM9yFuYKWcieTUGGghVFsNZxhMj3a04BmBZdffbDdrFRs+5n6k9YmdesL4pn9i8sI5nJSCle7GCERVrxD2FHbMfdqlLqxFc80nuxNM=
  - secure: elRNmbBJPne7Itznbdqyv7ZgC/3rVWz9BL3CEszr4i3/YFJQQXBF/vrjecHWymbM4tFgT94sAqclbRF8tKvRBvqkuSyfEGPFINzHR/srFlePJIgfpZkS9zpQ34rhsrqoOC+l7AtDemMSAdiEXed94CFCiIpMuPAnHmteYUcf2CxJoUhqIdgWQUrL/OncBhn+4QbJ+XHV9Gg8Xunw1rkduwy2LW1ygX6VQcpU9MH1rPPZsNo/QXP0a5SR5ZhMhJN0LjmDe6md2gP9nEAKFvAIRkprMFmiRQvLRKonN8e+n7ota4ccxegW65hvMzZafm8RG70ZS6okwrOeosug1s7sHYty4+Y9miuQFZbCp8am1h08TB0ZstxD1p6PP2nx4U2CXW+qfnVovM1CXqKsR49rG3T15gOj6oHcykX5xXDI7caY3Yx6z0SjK0pJdRJ3p+ZiPJlKd8OK6YWfFJgLn4iAdw++lXx4Qyo06afAi7D04jLEmfjVjcDHPQfbjSDwfB1bCrvyJ6Aeyts6UYSzJBeOyVVwTr8B4Lsmz6oh1iVwR0aPn1AGj/BbVUufzGVisKwrVMEftppQ7sAGnoTMWx4EJyB4XbP5nALWmGmG/3Jtdk2ek2v6aFbPqfht4vd39nDvuQLRSDxHfP3tCyvGQvTP2xj10wWklhBBRoNpIR/ywrA=
install:
- docker build -f Dockerfile.amd64 -t ${IMAGE} .
script: skip
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- echo "${TRAVIS_BUILD_NUMBER}"
- if [[ "${TRAVIS_BRANCH}" == *test* ]]; then docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER};
  docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}; echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}${TRAVIS_BUILD_NUMBER}";
  else docker tag ${IMAGE} ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}; docker push ${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH};
  echo "${DOCKERHUB}/${IMAGE}:${TRAVIS_BRANCH}"; fi
notifications:
  email:
    on_success: never
    on_failure: never
